### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [andrey-lepekhin/Async_API_sprint_2#28]
Приветствую!

Вы хорошо постарались, но над SOLID еще нужно поработать.
По тестам замечаний нет.

1. [исправить] При инъекции внешнего [сервиса](https://github.com/andrey-lepekhin/Async_API_sprint_2/blob/2fa428ed2701f3a2f35e3442592a1afd544f3231/fastapi-solution/src/services/genre.py#L52) лучше использовать абстрактный класс. Тоже самое касается и redis. Проблемы могут возникнуть, когда будет принято решение заменить redis на memcached, а es на что-то другое.
Как это может быть реализовано, например для redis:
    ```
    from abc import ABC
    
    class AsyncCacheStorage(ABC):
        @abstractmethod
        async def get(self, key: str, **kwargs):
            pass
    
        @abstractmethod
        async def set(self, key: str, value: str, expire: int, **kwargs):
            pass
    ```
    В итоге запись redis: Redis = Depends(get_redis) можно заменить на cache: AsyncCacheStorage = Depends(get_redis), а es=Depends(get_elastic) заменится на text_search: FullTextSearch = Depends(get_elastic). Здесь главное, чтобы используемый класс кэширования/полнотекстового поиска реализовал методы абстрактного класса. В итоге, если необходимо будет заменить redis на memcached, то надо будет только изменить cache: AsyncCacheStorage = Depends(get_memcached).
2. [исправить] [Методы](https://github.com/andrey-lepekhin/Async_API_sprint_2/blob/2fa428ed2701f3a2f35e3442592a1afd544f3231/fastapi-solution/src/services/base.py#L15) абстрактного класса не должны содержать какой-то конкретной логики, на то они и абстрактные :) По сути, в абстрактном классе вы просто описываете интерфейс, который диктует классам наследникам обязательное присутствие тех или иных методов. А уже конкретная реализация метода описывается в классе-наследнике. Тоже самое касается и [конструктора](https://github.com/andrey-lepekhin/Async_API_sprint_2/blob/2fa428ed2701f3a2f35e3442592a1afd544f3231/fastapi-solution/src/services/base.py#L12) (в нем не стоит привязываться к конкретной реализации полнотекстового поиска). Его лучше определить непосредственно в классе-наследнике.
Рекомендую ознакомиться с данной [статьей](https://realpython.com/python-interface/) про различные подходы реализации интерфейсов.
3. [можно лучше] С развитием проекта в тестах фикстур будет все больше и больше, и их нужно систематизировать. Можно вынести в отдельный файл (затем добавлять другие файлы, логически разделяя их) и тем самым облегчим conftest.py. Для этого в conftest.py есть [pytest_plugins](https://docs.pytest.org/en/latest/how-to/fixtures.html)

**Comment by andrey-lepekhin** [comment]
Поправили всё, разве что абстрактный класс для редиса не стали делать потому что у нас нет логики кэша внутри проекта, он реализуется через внешний плагин. И там поменять редис на что-то другое - вопрос несколькких строк, -- кажется не стоит ради этого делать абстрактный класс.

**Comment by andrey-lepekhin** [comment]
Открыл, чтобы issue была виднее ревьюеру

**Comment by BigDeepBlue** [comment]
Принято!
